### ISSUE TITLE
Does it work on Ubuntu?

### ISSUE THREAD

**Issue by euberdeveloper** [nomadhoc/sound-play#10]
On ubuntu it seems not to work: 

![image](https://user-images.githubusercontent.com/33126163/120545350-d51ccf80-c3ee-11eb-86fa-d9062f50c1d7.png)

**Comment by austinyearlykim** [comment]
i believe this is windows only; i came here with the exact same error log @euberdeveloper

**Comment by apolle** [comment]
Like it's written in the docs, right now Linux is not supported. But things may possibly change the future if we have more use cases.
