### ISSUE TITLE
sound' has been declared but its value has never been read

### ISSUE THREAD

**Issue by Lardu** [nomadhoc/sound-play#3]
Cannot find declaration file for module 'sound play'. "E: / work / work > Src / CMUI / node > modules / sound play / build / main. JS" implicitly has the type "any".

Try `npm install @types/sound-play` if it exists or add a new declaration (.d.ts) file containing `declare module 'sound-play';`ts(7016)

i don't know how to fix it.or because my use way is wrong.

**Comment by nomadhoc** [comment]
@Lardu There is no type definitions for this package yet. You may want to define and declare its type by yourself.

**Comment by Lardu** [comment]
> @Lardu此软件包尚无类型定义。您可能需要自己定义和声明其类型。

Thank you very much. It worked
