### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Kato1205** [nomadhoc/sound-play#6]
Are there any plans to add pause features where you can pause, and start playing back from where you left off?

as well as a stop feature? this may be a duplicate to the other suggestion but that was far back from 2019

**Comment by ilehoang** [comment]
@Kato1205 Unfortunately not, there isn't a real pause/stop function without using a third party media player. 

The closest one to stop is `killall afplay` on Mac. 
On Windows, perhaps something like [this](https://stackoverflow.com/questions/44317018/how-to-stop-sounds-with-mediaplayer-c-sharp) may work.

**Comment by Kato1205** [comment]
@ilehoang Thanks a lot, a stop feature would already be useful, looking forward to it in the future
