### ISSUE TITLE
How to loop

### ISSUE THREAD

**Issue by mafanwei** [nomadhoc/sound-play#8]
I want play music with loop.
How to do that?

**Comment by apolle** [comment]
@mafanwei There isn't looping feature yet. Have you tried making a custom loop using Javascript? 
For example, `setInterval(() => {...}, AUDIO_FILE_LENGTH);`

**Comment by Linbubin** [comment]
I think`while true` is better than `setInterval`
```js
while(true){
   await sound.play(filename)
}
```

**Comment by apolle** [comment]
Is there any reasons for while over setInterval? 

There are quite a few problems with while IMO, but firstly, I'm not sure if while will loop the sound properly here. Have you tried running the code?
