### ISSUE TITLE
What to do about types?

### ISSUE THREAD

**Issue by BrenekH** [nomadhoc/sound-play#9]
I use Typescript for most of my projects and just found this wonderful package for my latest project. However, types are not shipped with the package nor are they published using [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

Luckily, the type declaration was fairly easy to write, but it's way easier for consumers if the definition is done as part of the package and distributed via npm. To accomplish this, a change to the `package.json` and one line in a file is all that's required:

src/index.d.ts
```typescript
export function play(path: string, volume?: number): Promise<unknown>;
```

package.json
```json
...
"types": "./src/index.d.ts",
...
```

I have a branch on my fork with the changes all ready to go but I wanted to get the opinion of the maintainer(s) before submitting a PR.

So I guess my question is this, should the types be embedded into the package here or should they be contributed to DefinitelyTyped instead?

> Note: I have already looked at #3 but it doesn't give an answer to my question that I can tell.

**Comment by BrenekH** [comment]
~~I've opened up a [PR on DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53649) if anyone wants to go review the changes, maintainer or otherwise.~~ The PR has been merged, types are available by installing `@types/sound-play`.

**Comment by apolle** [comment]
Awesome!
